---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  sources:
    - name: Watch for any updated table
      servicenow.itsm.records:
        table: sc_request
        interval: 5
        # timezone: UTC
        remote_servicenow_timezone: Europe/Paris

  rules:

    - name: New record created and debug
      condition: event.sys_id is defined
      action:
        debug:
